package server.model.databasemediator;

import shared.wares.Basket;
import shared.wares.Product;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;

// Young

public interface DAOCustomerInterface extends CollectionDAOInterface{
	// GETTING

	/**
	 * Accesses the Database and creates a list of all products currently stored in the Database sub-tables
	 *
	 * @return List containing every single product currently stored in all sub-tables
	 * @throws SQLException Thrown when Database access is not possible <br>
	 *                      Often caused by Database not being online
	 */
	List<Product> requestAllProducts() throws SQLException;

	// SETTING

	/**
	 * Accesses the Database and creates an Order and OrderSpec using the orderTime to access the generated
	 * orderNo from the order table to use as a Partial Primay Key in the orderSpec table
	 *
	 * @param cvr       Company CVR used as Identification for the Customer
	 * @param orderTime Time used for temporary identification, should preferably be generated by the Client when the Order is sent
	 * @param basket    Basket containing the wares of which to place in an orderSpec
	 * @return True if order and orderSpec were successfully created, false otherwise
	 * @throws SQLException Thrown when Database access is not possible <br>
	 *                      Often caused by Database not being online
	 */
	boolean createOrder(int cvr, LocalDateTime orderTime, Basket basket) throws SQLException;
}
